### ISSUE TITLE
Symfony 3.0.4 - sidebar - token not found

### ISSUE THREAD

**Issue by ikerib** [avanzu/AdminThemeBundle#101]
Hi,
I installed the bundle and I me trying to add some menus to the sidebar using https://github.com/avanzu/AdminThemeBundle/blob/master/Resources/docs/sidebar_navigation.md . 

I created a Model in my bundle and imported the interface needed funciontions.

Then I creted a new folder EventListener and a new class MyMenuItemListListener.php I copyed the code and added some menu items

```
protected function getMenu(Request $request) {
        // Build your menu here by constructing a MenuItemModel array
        $menuItems = array(
            $blog = new MenuItemModel('ItemId', 'ItemDisplayName', 'category_index', array(/* options */), 'iconclasses fa fa-plane')
        );

        // Add some children

        // A child with an icon
        $blog->addChild(new MenuItemModel('ChildOneItemId', 'ChildOneDisplayName', 'category_index', array(), 'fa fa-rss-square'));

        // A child with default circle icon
        $blog->addChild(new MenuItemModel('ChildTwoItemId', 'ChildTwoDisplayName', 'category_index'));
        return $this->activateByRoute($request->get('_route'), $menuItems);
    }
```
Nothing more changed here (namespace of course).

After that I created my service like this:

```
parameters:
    my_admin_bundle.menu_listener.class: AppBundle\EventListener\MyMenuItemListListener

services:
    my_admin_bundle.menu_listener:
        class: AppBundle\EventListener\MyMenuItemListListener
        tags:
            - { name: kernel.event_listener, event:theme.sidebar_setup_menu, method:onSetupMenu }
```

Now If I go to my app I can see an error:

`Token not found`

I´m I missing something?
