### ISSUE TITLE
Default Symfony 404 template overwrite by AvanzuAdminThemeBundle

### ISSUE THREAD

**Issue by pich** [avanzu/AdminThemeBundle#119]
In Symfony 2.8.8 if AvanzuAdminThemeBundle is placed after TwigBundle in AppKerenl.php $bundles  its overwrite default Symfony 404 error page as you can see in the attachment.   
If it's placed before TwigBundle i get default 404 symfony error page as expected.
This issue occure only in urls that begins with "/admin" if you don't have route that match "/admin" prefix.
![zrzut ekranu 2016-07-07 o 08 44 49](https://cloud.githubusercontent.com/assets/549441/16644945/c0100d30-4420-11e6-8fe0-9b913b04303b.png)

**Comment by hjanuschka** [comment]
we are using `KwrzTwigExceptionBundle` to handle error's - having different error pages for admin/backend and frontend

sample `config.yml`
```
kwrz_twig_exception:
  enabled: true
  with_debug: true
  handlers:
      #403 auth failed should display a non backend error
    - { regex: ^\/backend, template: "FXFFrontendBundle:Exception:errorDefault.html.twig", status_code: [403]}
    - { regex: ^\/backend, template: "FXFAdminBundle:Exception:errorDefault.html.twig"}
    - { regex: ^\/, template: "FXFFrontendBundle:Exception:errorDefault.html.twig"}

```

@pich  maybe that helps?
