### ISSUE TITLE
Unrecognized option "knp_menu" under "avanzu_admin_theme"

### ISSUE THREAD

**Issue by numerogeek** [avanzu/AdminThemeBundle#180]
Hello,
I've got trouble when using the base_layout.

I tried to override it, and it tells me : 

Method "knp_menu" for object "Avanzu\AdminThemeBundle\Helper\ContextHelper" does not exist in app/Resources/AvanzuAdminThemeBundle/views/layout/base-layout.html.twig

I tried to add the knp_menu.enabled in the config but it says :
Unrecognized option "knp_menu" under "avanzu_admin_theme"

I think that the twig globals are not passed to my view override. Any idea ?

thanks !

**Comment by shakaran** [comment]
@numerogeek are you using master or 1.3 version? Could you copy your current config ans base-layout override to see if there are something different?

**Comment by benr77** [comment]
This is since upgrading to the latest beta 7 release. I am suffering from the same issue.

**Comment by benr77** [comment]
I had to downgrade back to `2.0.0-beta.5` to get my configuration to be accepted.
Are the configuration changes documented anywhere?

**Comment by shakaran** [comment]
@numerogeek @benr77 I push a fix https://github.com/avanzu/AdminThemeBundle/commit/a6afac02b91022a7e27bd98ea0562e1383a6022d related to ContextHelper config in master, please test if you can so this should be fixed

**Comment by benr77** [comment]
It doesn't seem to have fixed my problem:

In my composer.json

`"avanzu/admin-theme-bundle": "dev-master#a6afac02b91022a7e27bd98ea0562e1383a6022d"`

then `composer update avanzu/admin-theme-bundle`

I get the following error

```
[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
  Unrecognized options "knp_menu, theme" under "avanzu_admin_theme"
```
If I revert back to `2.0.0-beta.5` it works again. 

Here is my configuration

```
avanzu_admin_theme:
  knp_menu:
    enable : true
  theme:
    default_avatar: bundles/avanzuadmintheme/img/avatar.png
    skin: skin-blue  # see skin listing for viable options
    fixed_layout: false      # -------------------------------------------------------
    boxed_layout: false      # these settings relate directly to the "Layout Options"
    collapsed_sidebar: false      # described in the adminlte documentation
    mini_sidebar: false      # -------------------------------------------------------
    control_sidebar: true      # controls whether the right hand panel will be rendered
    widget:
      collapsible: false
      removable: false
      solid: true
      use_footer: false

```

**Comment by shakaran** [comment]
@benr77 thanks for your testing! I push new updates in master, please test if you can for receive your new feedback

**Comment by numerogeek** [comment]
@shakaran Sounds good for knp_menu but if you want to customize the skin it does not work. 
In fact, in the ContextHelper, you set the default in : 
 $resolver->setDefaults([
            'use_twig' => true,
            'use_assetic' => true,
            'options' => [],
            'skin' => 'skin-blue',

But in the Configuration, you put the skin option under the "theme" node.

When I try to change the skin:

avanzu_admin_theme:
    theme:
        skin: skin-black

 it does not change anything and {{ dump(avanzu_admin_context.option) }} gives me an empty array.

**Comment by shakaran** [comment]
@numerogeek the skin param don't should appear under _avanzu_admin_context.option_, if should be under _avanzu_admin_context.skin_ directly

```
avanzu_admin_theme:
    theme:
        skin: skin-black
```

Take in mind that _avanzu_admin_context_ is a shorcut to class _avanzu_admin_theme.context_helper_ 

All under the "context" should be present:

`{{ dump(avanzu_admin_context.skin) }}`

Another case could be via the twig function "body_class" which use some default layouts in the bundle templates:

`body_class({'skin': 'skin-black'})`

The body_class has more params like _fixed_layout, boxed_layout, collapsed_sidebar, mini_sidebar_ . The full config for that is:

```
body_class({
    'skin': 'skin-black',
    'fixed_layout': 'true',
    'boxed_layout': 'true',
    'collapsed_sidebar': 'true',
    'mini_sidebar': 'true',
})
```

**Comment by numerogeek** [comment]
@shakaran When I try to dump {{ dump(avanzu_admin_context.skin) }} 
I got
> Method "skin" for object "Avanzu\AdminThemeBundle\Helper\ContextHelper" does not exist

**Comment by numerogeek** [comment]
@shakaran I think that the configuration is overwritten with default value when the container builds.

**Comment by numerogeek** [comment]
@shakaran Update: 
In the AvanzuAdminExtension class : 

`    public function load(array $configs, ContainerBuilder $container)
    {
        $baseConfiguration = new Configuration();
        
        // Load the configuration from files
        try
        {
            $configs = $container->getExtensionConfig($this->getAlias());
        }
        catch(InvalidConfigurationException $e)
        {
            echo 'AvanzuAdminBundle:' . $e->getMessage() . PHP_EOL;
            $configs = [];
        }
....
`


$configs is resetted with the default value. Why  do you do this  `$configs = $container->getExtensionConfig($this->getAlias());` ?

**Comment by shakaran** [comment]
@numerogeek before to this fixes, when you have a invalid config value set (for example an invented key or unexistant). You will get a exception that will avoid render anything.

In your case, it seems that you get a InvalidConfigurationException, that means that your config has some invalid value, and you should see a message with "AvanzuAdminBundle" string in console or printed.

The problem here, is that it should fallback to base config, which I set a $config = [] array value, and probably it should fallback to base configuration instead.

The $container->getExtensionConfig($this->getAlias()); is needed to fetch and validate the current config before to apply or read the values in config. That means, set a base config, override with the values set by the user and after apply the final result.

So, please watch if you are receiving a message with AvanzuAdminBundle previously with the invalid configuration. I will push a fix for the base configuration.

**Comment by numerogeek** [comment]
@shakaran 
Here is my config: 
```
avanzu_admin_theme:
    bower_bin: %bower_bin% # that's the default value
    use_assetic: true
```
To reproduce: Try to clear your cache, set a custom bower_bin path (I need it for travis because travis don't store it in /usr/local/bin) and try to print the bower path selected by the load configuration.

I suspect that's exactly the same for the skin option etc...

**Comment by shakaran** [comment]
@numerogeek do you have defined the parameter %bower_bin% ? Are you sure that it is valid without quotes?

I mean:

```
parameters:
    bower_bin: "your custom bower bin for travis"

avanzu_admin_theme:
    bower_bin: "%bower_bin%" # See the quoting here
    use_assetic: true
```

Probably the problem come from the invalid parameter or the missing quote of the parameter.

Make a composer update to master, and watch in the update, if you get a warning line starting with the text "AvanzuAdminBundle: invalid config"
