### ISSUE TITLE
Wrong css images path

### ISSUE THREAD

**Issue by nexxome** [avanzu/AdminThemeBundle#64]
For example on the login page template there is a checkbox with a background image from the iCheck plugin called blue.png. 

``` css
.icheckbox_square-blue,.iradio_square-blue{
...
background:url(blue.png) no-repeat;
}
```

The css source is "bundles/avanzuadmintheme/static/dev/styles/admin-lte-all.css" so the image path is "bundles/avanzuadmintheme/static/dev/styles/blue.png" which is wrong because the real source css is from "bundles/avanzuadmintheme/vendor/adminlte/plugins/iCheck/square/".

**Comment by JuliusKoronci** [comment]
I have the same issue

**Comment by sylvaincombes** [comment]
Same issue here too

**Comment by lucasaba** [comment]
I'm experiencing the same problem with the colorpicker plugin. In my case, saturation.png, hue.png and alpha.png are not correctly mapped.

A possible solution (in my app): add them in app/config/configg.yml

A better solution in the bundle would be to update [assets.yml](https://github.com/avanzu/AdminThemeBundle/blob/master/Resources/config/assets.yml):
```
common_js:
    inputs:
        - '@AvanzuAdminThemeBundle/Resources/public/vendor/jquery/dist/jquery.js'
        - '@AvanzuAdminThemeBundle/Resources/public/vendor/jquery-ui/ui/jquery-ui.js'
cp_saturation_img:
    inputs:
        - "%kernel.root_dir%/../vendor/avanzu/admin-theme-bundle/Resources/public/vendor/adminlte/plugins/colorpicker/img/saturation.png"
    output: 'bundles/avanzuadmintheme/static/dev/styles/img/saturation.png'
cp_hue_img:
    inputs:
        - "%kernel.root_dir%/../vendor/avanzu/admin-theme-bundle/Resources/public/vendor/adminlte/plugins/colorpicker/img/hue.png"
    output: 'bundles/avanzuadmintheme/static/dev/styles/img/hue.png'
cp_alpha_img:
    inputs:
        - "%kernel.root_dir%/../vendor/avanzu/admin-theme-bundle/Resources/public/vendor/adminlte/plugins/colorpicker/img/alpha.png"
    output: 'bundles/avanzuadmintheme/static/dev/styles/img/alpha.png'
```

I'm looking for a better solution....
